version: "3.8"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    ports:
      - "8001:8000" # Laravel Artisan
    networks:
      - laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: W@ll3ts2024!
      MYSQL_DATABASE: wallets
      MYSQL_USER: laravel
      MYSQL_PASSWORD: L@r@v3l2024!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  frontend:
    image: node:20
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8080:8080"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
