services:
  php-nginx:
    container_name: php-nginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/extra-php.ini:/usr/local/etc/php/conf.d/extra-php.ini
      - ./docker/php/extra-php-fpm.conf:/etc/php8/php-fpm.d/www.conf
    ports:
      - "8001:80" #http
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: W@ll3ts2024!
      MYSQL_DATABASE: wallets
      MYSQL_USER: laravel
      MYSQL_PASSWORD: L@r@v3l2024!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge